Adding the possibility to charge value for the service instead of the type

diff --git a/errant b/errant
--- a/errant
+++ b/errant
@@ -26,8 +26,13 @@ TECHNOLOGY=""
 QUALITY=""
 INTERFACE=""
 LOGFILE=""
+UPLOAD=""
+DOWNLOAD=""
+RTT_AVG=""
+LOSS=""
 
-while getopts  "o:c:t:q:i:p:l:rhd" flag
+
+while getopts  "o:c:t:q:i:p:l:u:d:R:rhd" flag
 do
     case $flag in
         o) OPERATOR=$OPTARG;;
@@ -36,16 +41,20 @@ do
         q) QUALITY=$OPTARG;;
         i) INTERFACE=$OPTARG;;
         l) LOGFILE=$OPTARG;;
+        u) UPLOAD=$OPTARG;;
+        d) DOWNLOAD=$OPTARG;;
+        R) RTT_AVG=$OPTARG;;
+        L) LOSE=$OPTARG;;
         r) REMOVE=true;;
         d) DRY_RUN=true;;
         p) PERIODIC=$OPTARG;;
-        h) echo "Usage: errant -o operator -c country -t technology -q quality -i interface [-p period] [-l logfile] [-r] [-d] [-h]" ; exit ;;
+        h) echo "Usage: errant { -o operator -c country -t technology -q quality | -u upload_speed [-d download_speed] -R RTT } -i interface [-p period] [-L loss] [-l logfile] [-r] [-d] [-h]" ; exit ;;
     esac
 done
 
 # Log file header
-if [ ! -z $LOGFILE ] ; then
-    echo "time,operator,country,technology,quality,download,upload,rtt" > $LOGFILE
+if [ -n $LOGFILE ] ; then
+    echo "time,operator,country,technology,quality,download,upload,rtt,loss" > $LOGFILE
 fi
 
 # Remove rules
@@ -53,11 +62,12 @@ if [ "$REMOVE" = true ]; then
 
     # Check arguments are correct
     if [ -z "$OPERATOR" ] && [ -z "$COUNTRY" ] && [ -z "$TECHNOLOGY" ] \
-                          && [ -z "$QUALITY" ] && [ -z "$INTERFACE" ]; then
+                          && [ -z "$QUALITY" ] && [ -z "$INTERFACE" ] \
+                          && [ -z "$UPLOAD" ] && [ -z "$DOWNLOAD" ] && [ -z "$RTT_AVG" ]; then
         echo "Removing shaping rules"
         
         # Remove module IFB
-        go rmmod ifb 2>/dev/null
+        go ip link delete $VIRTUAL type ifb
 
         # Remove all TC policies
         for INTERFACE in $( ifconfig -a | sed 's/[: \t].*//;/^$/d' | grep -v ifb ) ; do
@@ -72,13 +82,24 @@ if [ "$REMOVE" = true ]; then
     fi
     
 else
-    if [ -z "$OPERATOR" ] || [ -z "$COUNTRY" ] || [ -z "$TECHNOLOGY" ] \
-                          || [ -z "$QUALITY" ] || [ -z "$INTERFACE" ]; then
+
+    DOWNLOAD=${DOWNLOAD:-UPLOAD}
+    if [ -n "$UPLOAD" ] && [ -n "$DOWNLOAD" ] && [ -n "$RTT_AVG" ]; then
+        OPERATOR=${OPERATOR:-"universal"}
+        COUNTRY=${COUNTRY:-"universal"}
+        TECHNOLOGY=${TECHNOLOGY:-"universal"}
+        QUALITY=${QUALITY:-"universal"}
+    fi
+    
+    if [ -z "$INTERFACE" ]; then
+        echo "You should specify the interface"
+    elif [ -z "$OPERATOR" ] || [ -z "$COUNTRY" ] \
+         || [ -z "$TECHNOLOGY" ] || [ -z "$QUALITY" ]; then
         echo "You should specify all of operator,country, technology, quality and interface"
     else
         echo "Imposing shaping on interface: $INTERFACE"
         
-        if [ ! -z $PERIODIC ] ; then
+        if [ -n $PERIODIC ] ; then
             if ! [[ "$PERIODIC" =~ ^[0-9]+$ ]] ; then
                 echo "Wrong periodic shaping value. Only integers allowed."
                 exit
@@ -88,70 +109,84 @@ else
         fi
         
         while true ; do
-            # Search for profile
-            values=$( python3 sample_from_distribution.py $OPERATOR $COUNTRY $TECHNOLOGY $QUALITY )
-                    
-            if [ "$values" = "error" ] ; then
-                echo "Cannot find selected profile"
-                exit
-            else
-            
-                # Print infos
-                echo "Imposing profile:"
-                echo "    Operator:   $OPERATOR"
-                echo "    Country:    $COUNTRY"
-                echo "    Technology: $TECHNOLOGY"
-                echo "    Quality:    $QUALITY"
-                
+            if [ -z "$UPLOAD" ] && [ -z "$DOWNLOAD" ] && [ -z "$RTT_AVG" ]; then
+                # Search for profile
+                values=$( python3 sample_from_distribution.py $OPERATOR $COUNTRY $TECHNOLOGY $QUALITY )
+                        
+                if [ "$values" = "error" ] ; then
+                    echo "Cannot find selected profile"
+                    exit
+                fi
+
                 DOWNLOAD=$(echo $values | cut -d " " -f 1)
                 UPLOAD=$(echo $values | cut -d " " -f 2)
                 RTT_AVG=$(echo $values | cut -d " " -f 3)
-                
-                echo "Parameters are:"
-                echo "    Download [kbps]: $DOWNLOAD"
-                echo "    Upload [kbps]:   $UPLOAD"
-                echo "    RTT [ms]:        $RTT_AVG"
-                
-                # Write Log if needed
-                if [ ! -z $LOGFILE ] ; then
-                    echo "$(date +%s),$OPERATOR,$COUNTRY,$TECHNOLOGY,$QUALITY,$DOWNLOAD,$UPLOAD,$RTT_AVG" >> $LOGFILE
+            fi
+
+            if [ -n $LOSS ]; then
+                if ! [[ "$LOSS" =~ ^[0-9]+$ ]]; then
+                    echo "Wrong loss shaping value. Only integers allowed. Defaulting to 0%."
+                    LOSS="0"
                 fi
-                
-                # Impose shaping
-                
-                # Create virtual interfaces
-                go ip link add $VIRTUAL type ifb
-                go ip link set dev $VIRTUAL up
-                
-                # Create rules
-                # Clear old
-                go tc qdisc del root dev $INTERFACE 2>/dev/null       # clear outgoing
-                go tc qdisc del dev $INTERFACE handle ffff: ingress 2>/dev/null    # clear incoming
-                go tc qdisc del root dev $VIRTUAL 2>/dev/null
+            fi
+            LOSS=${LOSS:-"0"}
 
 
-                # Create Device Pipes
-                go tc qdisc add dev $INTERFACE handle ffff: ingress
-                go tc filter add dev $INTERFACE parent ffff: protocol ip u32 match u32 0 0 \
-                                                action mirred egress redirect dev $VIRTUAL
+            # Print infos
+            echo "Imposing profile:"
+            echo "    Operator:   $OPERATOR"
+            echo "    Country:    $COUNTRY"
+            echo "    Technology: $TECHNOLOGY"
+            echo "    Quality:    $QUALITY"
+            
+            echo "Parameters are:"
+            echo "    Download [kbps]: $DOWNLOAD"
+            echo "    Upload [kbps]:   $UPLOAD"
+            echo "    RTT [ms]:        $RTT_AVG"
+            echo "    LOSS [%]:        $LOSS"
+            
+            # Write Log if needed
+            if [ -n $LOGFILE ] ; then
+                echo "$(date +%s),$OPERATOR,$COUNTRY,$TECHNOLOGY,$QUALITY,$DOWNLOAD,$UPLOAD,$RTT_AVG,$LOSS" >> $LOGFILE
+            fi
+            
+            # Impose shaping
+            
+            # Create virtual interfaces
+            go ip link add $VIRTUAL type ifb
+            go ip link set dev $VIRTUAL up
+            
+            # Create rules
+            # Clear old
+            go tc qdisc del root dev $INTERFACE 2>/dev/null       # clear outgoing
+            go tc qdisc del dev $INTERFACE handle ffff: ingress 2>/dev/null    # clear incoming
+            go tc qdisc del root dev $VIRTUAL 2>/dev/null
 
 
-                # INCOMING
-                # Speed
-                go tc qdisc add dev $VIRTUAL root handle 2: htb default 10
-                go tc class add dev $VIRTUAL parent 2:  classid 2:1  htb rate $DEFAULT_DOWNLOAD
-                go tc class add dev $VIRTUAL parent 2:1 classid 2:10 htb rate ${DOWNLOAD}kbit
+            # Create Device Pipes
+            go tc qdisc add dev $INTERFACE handle ffff: ingress
+            go tc filter add dev $INTERFACE parent ffff: protocol ip u32 match u32 0 0 \
+                                            action mirred egress redirect dev $VIRTUAL
 
 
-                # OUTGOING
-                # Speed
-                go tc qdisc add dev $INTERFACE root handle 1: htb default 11
-                go tc class add dev $INTERFACE parent 1:  classid 1:1  htb rate $DEFAULT_UPLOAD
-                go tc class add dev $INTERFACE parent 1:1 classid 1:11 htb rate ${UPLOAD}kbit
-                # Delay
-                go tc qdisc add dev $INTERFACE parent 1:11 handle 10: netem delay ${RTT_AVG}ms
-                
-            fi 
+            # INCOMING
+            # Speed
+            go tc qdisc add dev $VIRTUAL root handle 2: htb default 10
+            go tc class add dev $VIRTUAL parent 2:  classid 2:1  htb rate $DEFAULT_DOWNLOAD
+            go tc class add dev $VIRTUAL parent 2:1 classid 2:10 htb rate ${DOWNLOAD}kbit
+            # Loss
+            go tc qdisc add dev $VIRTUAL parent 2:10 handle 20: netem loss random ${LOSS}
+
+            # OUTGOING
+            # Speed
+            go tc qdisc add dev $INTERFACE root handle 1: htb default 11
+            go tc class add dev $INTERFACE parent 1:  classid 1:1  htb rate $DEFAULT_UPLOAD
+            go tc class add dev $INTERFACE parent 1:1 classid 1:11 htb rate ${UPLOAD}kbit
+            # Delay
+            go tc qdisc add dev $INTERFACE parent 1:11 handle 10: netem delay ${RTT_AVG}ms
+            # Loss
+            go tc qdisc add dev $VIRTUAL parent 2:10 handle 20: netem loss random ${LOSS}
+
             
             if [ -z $PERIODIC ] ; then
                 break
